Imports System.IO
Imports System.Reflection
Imports System.Threading
Imports System.Windows.Forms
Imports HarmonyLib
Imports TaleWorlds
Imports TaleWorlds.Core
Imports TaleWorlds.DotNet
Imports TaleWorlds.Engine
Imports TaleWorlds.InputSystem
Imports TaleWorlds.MountAndBlade
Imports TaleWorlds.MountAndBlade.View

Namespace Global.BetterExceptionWindow
    Public Class Main
        Inherits MBSubModuleBase
        'Private Sub PatchNativeAPI2NetBoundaries()
        '    Dim callbacksGeneratedTypes = GetAssemblyByDll("TaleWorlds.Engine.AutoGenerated.dll")
        '    Dim CallbacksGenerated = callbacksGeneratedTypes.GetTypes().ToList()
        '    For Each x In CallbacksGenerated
        '        Print(x.Name)
        '    Next
        'End Sub
        Private Sub LoadBetterExceptionMCMUI()
            Dim bewUIDllFilePath = BewBinDir & "\BetterExceptionWindowConfigUI.dll"
            If Not File.Exists(bewUIDllFilePath) Then
                'Print("Unable to load better exception window mcm ui. BetterExceptionWindowConfigUI.dll was not found. It's ok")
                Exit Sub
            End If
            Dim theDll = Assembly.LoadFrom(bewUIDllFilePath)
            Dim theSpecifiedModule = theDll.GetType("BetterExceptionWindowConfigUI.EntryPoint")
            Dim methodInf = theSpecifiedModule.GetMethod("Start")
            methodInf.Invoke(Nothing, New Object() {})
        End Sub
        Protected Overrides Sub OnBeforeInitialModuleScreenSetAsRoot()
            If DisableBewButterlibException Or IsDebugged Then
                DisableButterlibFull()
            End If
            ControlPanelMcmSupport()
        End Sub
        Private Sub ControlPanelMcmSupport()
            Task.Delay(1000 * 2).ContinueWith(
                Sub()
                    If Not CheckIsAssemblyLoaded("Bannerlord.ButterLib.dll") Then
                        Exit Sub
                    End If
                    If CheckIsAssemblyLoaded("MCMv5.dll") AndAlso
                       CheckIsAssemblyLoaded("MCMv5.UI.dll") Then
                        LoadBetterExceptionMCMUI()
                    End If
                    Task.Delay(1000 * 3).ContinueWith(
                        Sub()
                            If IsFirstTime And DisableBewButterlibException Then
                                MsgBoxBannerlord("Better Exception Window Behaviour",
                                                "Better Exception Window detected Butterlib is also installed." & vbNewLine &
                                                "It will disable Butterlib exception window starting from this version." & vbNewLine & vbNewLine &
                                                "You can restore to old behaviour by unchecking Disable BewButterlib exception in mod option",
                                                Sub()
                                                    DisableBewButterlibException = True
                                                    IsFirstTime = False
                                                    SaveSettings()
                                                End Sub, Nothing, "I understand")
                            End If
                        End Sub
                    )
                End Sub)
        End Sub
        Private Sub DisableButterlibFull()
            If CheckIsAssemblyLoaded("Bannerlord.ButterLib.dll") Then
                DisableButterlibException()
            End If
        End Sub
        Protected Overrides Sub OnSubModuleLoad()
            ReadConfig()
            If EnableStdoutConsole Then SpawnConsole() Else StartLogger()
            InitPatch()
            If IsDebugged Then
            Else
                InitPatch()
            End If
        End Sub
    End Class
End Namespace
